USE [master]
GO

/****** Object:  Database [ReactDotnet]    Script Date: 23.06.2022. 20:16:05 ******/
CREATE DATABASE [ReactDotnet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ReactDotnet', FILENAME = N'E:\Microsoft SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\ReactDotnet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ReactDotnet_log', FILENAME = N'E:\Microsoft SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\ReactDotnet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReactDotnet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ReactDotnet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ReactDotnet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ReactDotnet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ReactDotnet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ReactDotnet] SET ARITHABORT OFF 
GO

ALTER DATABASE [ReactDotnet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ReactDotnet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ReactDotnet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ReactDotnet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ReactDotnet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ReactDotnet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ReactDotnet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ReactDotnet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ReactDotnet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ReactDotnet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ReactDotnet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ReactDotnet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ReactDotnet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ReactDotnet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ReactDotnet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ReactDotnet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ReactDotnet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ReactDotnet] SET RECOVERY FULL 
GO

ALTER DATABASE [ReactDotnet] SET  MULTI_USER 
GO

ALTER DATABASE [ReactDotnet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ReactDotnet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ReactDotnet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ReactDotnet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ReactDotnet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ReactDotnet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ReactDotnet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ReactDotnet] SET  READ_WRITE 
GO

